# Generated by Django 5.1.4 on 2024-12-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_close_at', models.DateTimeField()),
                ('start_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
            ],
        ),
    ]
